# Generated by Django 2.1.5 on 2019-01-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_programm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name',
            options={'verbose_name': 'Пицца', 'verbose_name_plural': 'Пиццы'},
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
    ]
