# Generated by Django 2.1.5 on 2019-01-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_programm', '0002_auto_20190108_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name',
            options={'verbose_name': 'Пиццу', 'verbose_name_plural': 'Пиццы'},
        ),
    ]
