# Generated by Django 2.1.5 on 2019-01-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='store',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
