# Generated by Django 2.1.5 on 2019-01-10 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_auto_20190110_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='good.Store', verbose_name='Магазин'),
        ),
    ]
