# Generated by Django 2.1.5 on 2019-01-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_auto_20190109_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='description',
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
